customhost = "employee.cjd4woj1ez0r.ap-south-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "addemployee3246"
customregion = "ap-south-1"
